language: go
arch:
  - amd64
  - ppc64le

go:
  - tip
  - "1.14.3"
  - "1.13.11"
  - "1.12.17"
  - "1.11.13"
  - "1.10.8"
  - "1.9.7"
  
go_import_path: github.com/coyim/otr3/
matrix:
  allow_failures:
    - go: tip

addons:
  apt:
    packages:
      - automake
      - libtool
      - libgcrypt11-dev
      - libgpg-error-dev

install: make deps
script: make ci

cache:
  apt:
